const { config } = require('dotenv');

config({ path: '.env' });

const { PORT, DB_URI, JWT_SECRET, JWT_EXPIRES_IN, ARCJET_ENV, ARCJET_KEY, QSTASH_TOKEN, QSTASH_URL, SERVER_URL, EMAIL_PASSWORD } = process.env;

module.exports = { PORT, DB_URI, JWT_SECRET, JWT_EXPIRES_IN, ARCJET_ENV, ARCJET_KEY, QSTASH_TOKEN, QSTASH_URL, SERVER_URL, EMAIL_PASSWORD };
